spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
server:
  http2:
    enabled: true
  port: 8080
  ssl:
    enabled: true
    key-store: ./keystore.jks
    key-store-password: password
    key-store-type: JKS
    key-alias: musicserv
